/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateProjectRequest { 
    /**
     * Project name, which identifies the project to the user
     */
    name: string;
    description?: string | null;
    /**
     * A color that is convenient for the user to identify the project
     */
    tint: string;
    /**
     * Project workspace id
     */
    workspace_id: number;
    /**
     * Project lead user id
     */
    lead_id: number;
}

