/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TaskStatusDto } from './taskStatusDto';
import { Priority } from './priority';


export interface TaskInfoDto { 
    /**
     * Id of the task
     */
    id: number;
    /**
     * Title of the task
     */
    title: string;
    description?: string | null;
    /**
     * Position index of the task
     */
    index: number;
    /**
     * 
     */
    status: TaskStatusDto;
    /**
     * Priority of the task
     */
    priority: Priority;
    due_date?: string | null;
    assigned_user_id?: number | null;
    /**
     * Id of the reporter
     */
    reporter_user_id: number;
    /**
     * created_at
     */
    created_at: string;
    /**
     * updated_at
     */
    updated_at: string;
    /**
     * Completed task
     */
    is_completed: boolean;
}
export namespace TaskInfoDto {
}


