/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Priority } from './priority';


export interface UpdateTaskRequest { 
    title?: string | null;
    description?: string | null;
    status_id?: number | null;
    priority?: Priority | null;
    /**
     * Due date
     */
    due_date: string;
    assigned_user_id?: number | null;
    reporter_user_id?: number | null;
}
export namespace UpdateTaskRequest {
}


