/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserInfoDto { 
    /**
     * ID of the user
     */
    id: number;
    /**
     * User first name
     */
    first_name: string;
    last_name?: string | null;
    /**
     * User email
     */
    email: string;
}

