/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserInfoDto } from './userInfoDto';


export interface WorkspaceExtendedDto { 
    /**
     * ID of the workspace
     */
    id: number;
    /**
     * Workspace name, which identifies the workspace to the user
     */
    name: string;
    description?: string | null;
    /**
     * Workspace owner user id
     */
    owner: UserInfoDto;
}

